POST http://siberiabirds.local/api/bird-genera/add HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: 1|UX8uap8TIeT8AwePvSqFqtWv4ycvdllECr6CFcvz8ed33903

{
    "title": "Апторнис",
    "title_latin": "Aptornis",
    "description": "Апторнис (лат. Aptornis) — род вымерших птиц отряда журавлеобразных. Крупные наземные птицы высотой около 80 см и массой до 25 кг обитали на островах Новой Зеландии с раннего миоцена до XIII века.",
    "bird_family_id": 1
}