POST http://siberiabirds.local/api/bird-families/add HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: 1|UX8uap8TIeT8AwePvSqFqtWv4ycvdllECr6CFcvz8ed33903

{
    "title": "Качурки",
    "title_latin": "Hydrobatidae",
    "description": "Небольшие, меньше голубя (размах крыльев около 40 см), морские птицы, в полёте несколько напоминающие ласточек.",
    "bird_order_id": 1
}