PUT http://siberiabirds.local/api/bird-families/edit/3 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|UX8uap8TIeT8AwePvSqFqtWv4ycvdllECr6CFcvz8ed33903

{
    "title": "Кариамовые",
    "title_latin": "Cariamidae",
    "description": "Наземные бегающие птицы 70—92 см длиной. Тело удлинённое, с длинной шеей и маленькой головой.",
    "bird_order_id": 1
}