POST http://siberiabirds.local/api/user-roles/add HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|UX8uap8TIeT8AwePvSqFqtWv4ycvdllECr6CFcvz8ed33903

{
    "title": "Test role"
}