POST http://siberiabirds.local/api/species-population-statuses/add HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: 1|UX8uap8TIeT8AwePvSqFqtWv4ycvdllECr6CFcvz8ed33903

{
    "title": "Крайне редкий",
    "description": ""
}